import { describe, it, expect, beforeAll } from 'vitest'
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { emitReactComponent, type PNode } from '../../../../src/lib/renderer/interactions/compile/emit-react'
import { validateBehaviour } from '../../../../src/lib/renderer/interactions/addressing'
import { initDefaultCatalog } from '../../../../src/lib/renderer/interactions/catalog'
import { todo } from './behaviour-fixtures'

const NODE_IDS = new Set(['page', 'addBtn', 'list', 'row'])

const presentation: PNode = {
  nodeId: 'page',
  role: 'container',
  children: [
    { nodeId: 'addBtn', role: 'button', text: 'Add' },
    { nodeId: 'list', role: 'list', children: [{ nodeId: 'row', role: 'item' }] },
  ],
}

beforeAll(() => initDefaultCatalog())

describe('emit-react (behaviour -> React)', () => {
  const source = emitReactComponent(todo(), presentation, { componentName: 'TodoDemo' })

  it('cross-checks: the behaviour validates against its node ids', () => {
    expect(validateBehaviour(todo(), NODE_IDS)).toEqual([])
  })

  it('emits idiomatic state, formulas, and a handler', () => {
    expect(source).toMatch(/const \[items, setItems\] = useState<any\[\]>\(\[\]\)/)
    expect(source).toContain('const isEmpty = (items.length === 0)')
    expect(source).toContain('setItems((prev) => [...prev, { label: "" }])')
  })

  it('weaves anchors, bound props, and the event handler', () => {
    expect(source).toContain('data-node-id="addBtn"')
    expect(source).toContain('disabled={isEmpty}')
    expect(source).toContain('onClick={handle_addBtn_press}')
  })

  it('emits the repeat with template anchor + instance key + referenced text', () => {
    expect(source).toContain('items.map((item) => (')
    expect(source).toContain('data-node-id="row"')
    expect(source).toContain('data-instance-key={item.id}')
    expect(source).toContain('{item.label}')
  })

  it('writes the generated component to disk for tsc to typecheck', () => {
    const dir = resolve(process.cwd(), 'src/lib/renderer/interactions/compile/__generated__')
    mkdirSync(dir, { recursive: true })
    writeFileSync(
      resolve(dir, 'TodoDemo.tsx'),
      `/* eslint-disable */\n// AUTO-GENERATED by compile.test.ts — proves the emitter output typechecks as React.\n${source}`
    )
    expect(source).toContain('export function TodoDemo()')
  })
})
