import { describe, it, expect, beforeAll } from 'vitest'
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { emptyPageInteractions, type PageInteractions } from '../../../../src/lib/renderer/interactions/ir'
import { normalize } from '../../../../src/lib/renderer/interactions/compile/normalize'
import { emitReactComponent, type PNode } from '../../../../src/lib/renderer/interactions/compile/emit-react'
import { validatePageInteractions } from '../../../../src/lib/renderer/interactions/addressing'
import { initDefaultCatalog } from '../../../../src/lib/renderer/interactions/catalog'

const NODE_IDS = new Set(['page', 'addBtn', 'list', 'row'])

/** The "todo" page: add to list, disable-when-empty, repeater rows showing labels. */
function todoIR(): PageInteractions {
  const ir = emptyPageInteractions()
  ir.variables.push({ id: 'items', type: { collection: 'object' }, scope: 'page', initial: [], source: 'local' })
  ir.derived.push({ id: 'isEmpty', expr: 'items.length == 0' })
  ir.interactions.push({
    on: { node: 'addBtn', trigger: { type: 'press' } },
    do: [{ type: 'collection.append', target: 'items', value: '{ label: "" }' }],
  })
  ir.bindings.push({ node: 'addBtn', prop: 'disabled', from: 'isEmpty' })
  ir.bindings.push({ node: 'row', prop: 'text', from: 'item.label' })
  ir.repeaters.push({ node: 'row', over: 'items', as: 'item' })
  return ir
}

const presentation: PNode = {
  nodeId: 'page',
  tag: 'div',
  children: [
    { nodeId: 'addBtn', tag: 'button', text: 'Add' },
    { nodeId: 'list', tag: 'ul', children: [{ nodeId: 'row', tag: 'li' }] },
  ],
}

beforeAll(() => initDefaultCatalog())

describe('normalize (sugar -> reactive graph)', () => {
  it('lowers each sugar element to the right node-kind', () => {
    const g = normalize(todoIR())
    const kinds = g.nodes.map((n) => n.kind)
    expect(kinds.filter((k) => k === 'derive')).toHaveLength(1) // isEmpty
    expect(kinds.filter((k) => k === 'fold')).toHaveLength(1) // append
    expect(kinds.filter((k) => k === 'sink')).toHaveLength(2) // two bindings
    expect(kinds).toContain('source') // items signal + press event
    const fold = g.nodes.find((n) => n.kind === 'fold')
    expect(fold && fold.kind === 'fold' && fold.state).toBe('items')
  })
})

describe('emit-react (IR -> React)', () => {
  const source = emitReactComponent(todoIR(), presentation, { componentName: 'TodoDemo' })

  it('cross-checks: the IR validates against its node ids', () => {
    expect(validatePageInteractions(todoIR(), NODE_IDS)).toEqual([])
  })

  it('emits idiomatic state, derived, and a handler', () => {
    expect(source).toMatch(/const \[items, setItems\] = useState<any\[\]>\(\[\]\)/)
    expect(source).toContain('const isEmpty = (items.length === 0)')
    expect(source).toContain('setItems((prev) => [...prev, { label: "" }])')
  })

  it('weaves anchors, bound props, and the event handler', () => {
    expect(source).toContain('data-node-id="addBtn"')
    expect(source).toContain('disabled={isEmpty}')
    expect(source).toContain('onClick={handle_addBtn_press}')
  })

  it('emits the repeater with template anchor + instance key + bound text', () => {
    expect(source).toContain('items.map((item) => (')
    expect(source).toContain('data-node-id="row"')
    expect(source).toContain('data-instance-key={item.id}')
    expect(source).toContain('{item.label}')
  })

  it('writes the generated component to disk for tsc to typecheck', () => {
    const dir = resolve(process.cwd(), 'src/lib/renderer/interactions/compile/__generated__')
    mkdirSync(dir, { recursive: true })
    writeFileSync(
      resolve(dir, 'TodoDemo.tsx'),
      `/* eslint-disable */\n// AUTO-GENERATED by compile.test.ts — proves the emitter output typechecks as React.\n${source}`
    )
    expect(source).toContain('export function TodoDemo()')
  })
})
