/**
 * Property tests for `invert()` and `rebase()` — Phase 1a of the history
 * redesign (`docs/history-redesign-plan.md`).
 *
 * The reference document model below is deliberately minimal and lives only in
 * this file. It is NOT the real applier (that is Phase 1) — it exists so the
 * semantic properties can be stated as "these two states are equal" rather than
 * as assertions about op lists, which is the only way to catch an inverse that
 * is well-formed but wrong.
 *
 * Op sequences are generated by interpreting random *intents* against a scratch
 * document and discarding the invalid ones. That matters: an arbitrary `Op[]`
 * would be full of sequences no committer could ever produce (setting a field
 * on a deleted shape, adding an id twice), and testing rebase against
 * unreachable input proves nothing while making shrunk counterexamples
 * unreadable.
 */

import { describe, expect, it } from 'vitest'
import fc from 'fast-check'
import type { EntityId, Op, Pos } from '../../../../src/lib/history/journal/op'
import { invert, invertAll } from '../../../../src/lib/history/journal/op'
import { isForeignConflict, rebase, rebased, resolve } from '../../../../src/lib/history/journal/rebase'
import type { Txn } from '../../../../src/lib/history/journal/journal-store'
import { CANVAS_SCOPE, LOCAL_ACTOR } from '../../../../src/lib/history/journal/journal-store'

// ---------------------------------------------------------------- reference model

interface Doc {
  /** `"<entity> <field>"` -> value */
  fields: Record<string, unknown>
  nodes: Record<EntityId, { parent: EntityId; pos: Pos }>
}

const ROOT = 'root'
const FRAME = 'f1'

/** A document with two containers and nothing else. */
function emptyDoc(): Doc {
  return { fields: {}, nodes: { [ROOT]: { parent: '', pos: 'a' }, [FRAME]: { parent: ROOT, pos: 'b' } } }
}

function applyOp(doc: Doc, op: Op): Doc {
  const fields = { ...doc.fields }
  const nodes = { ...doc.nodes }
  switch (op.t) {
    case 'set':
      if (nodes[op.entity]) fields[`${op.entity} ${op.field}`] = op.val
      break
    case 'add':
      nodes[op.entity] = { parent: op.parent, pos: op.pos }
      break
    case 'del':
      delete nodes[op.entity]
      // Delete wins: a deleted entity keeps no field state.
      for (const k of Object.keys(fields)) if (k.startsWith(`${op.entity} `)) delete fields[k]
      break
    case 'mov':
      if (nodes[op.entity]) nodes[op.entity] = { parent: op.parent, pos: op.pos }
      break
  }
  return { fields, nodes }
}

function applyAll(doc: Doc, ops: readonly Op[]): Doc {
  return ops.reduce(applyOp, doc)
}

// ---------------------------------------------------------------- generation

type Intent =
  | { k: 'set'; e: string; f: string; v: number }
  | { k: 'add'; e: string; p: string; pos: string }
  | { k: 'del'; e: string }
  | { k: 'mov'; e: string; p: string; pos: string }

const FIELDS = ['fill', 'x', 'name']
const POSITIONS = ['m', 's', 'w']

function intents(entities: readonly string[]): fc.Arbitrary<Intent[]> {
  const e = fc.constantFrom(...entities)
  const parent = fc.constantFrom(ROOT, FRAME)
  const pos = fc.constantFrom(...POSITIONS)
  return fc.array(
    fc.oneof(
      fc.record({ k: fc.constant('set' as const), e, f: fc.constantFrom(...FIELDS), v: fc.integer({ min: 0, max: 9 }) }),
      fc.record({ k: fc.constant('add' as const), e, p: parent, pos }),
      fc.record({ k: fc.constant('del' as const), e }),
      fc.record({ k: fc.constant('mov' as const), e, p: parent, pos }),
    ),
    { maxLength: 12 },
  )
}

/**
 * Interpret intents against `doc`, emitting only ops that are valid where they
 * land — and filling in the before-values (`was`, `wasParent`, `wasPos`) from
 * the live scratch state, exactly as a real committer would.
 */
function realize(doc: Doc, list: readonly Intent[]): { ops: Op[]; doc: Doc } {
  let cur = doc
  const ops: Op[] = []
  for (const i of list) {
    const node = cur.nodes[i.e]
    let op: Op | null = null
    switch (i.k) {
      case 'set':
        if (node) op = { t: 'set', entity: i.e, field: i.f, val: i.v, was: cur.fields[`${i.e} ${i.f}`] }
        break
      case 'add':
        if (!node) op = { t: 'add', entity: i.e, node: { tag: i.e }, parent: i.p, pos: i.pos }
        break
      case 'del':
        if (node) op = { t: 'del', entity: i.e, node: { tag: i.e }, parent: node.parent, pos: node.pos }
        break
      case 'mov':
        if (node) {
          op = {
            t: 'mov',
            entity: i.e,
            parent: i.p,
            pos: i.pos,
            wasParent: node.parent,
            wasPos: node.pos,
            via: 'mov-objects',
          }
        }
        break
    }
    if (op) {
      ops.push(op)
      cur = applyOp(cur, op)
    }
  }
  return { ops, doc: cur }
}

/**
 * Wrap gap ops as the transaction they would have been committed in. The gap is
 * typed as `Txn[]` rather than `Op[]` so a conflict can name the actor behind
 * it — see `isForeignConflict`.
 */
function gapOf(ops: Op[], actor: string = LOCAL_ACTOR): Txn[] {
  return ops.length === 0 ? [] : [{ seq: 1, actor, parentSeq: 0, scope: CANVAS_SCOPE, ops }]
}

const POOL_A = ['a1', 'a2', 'a3']
const POOL_B = ['b1', 'b2', 'b3']

// ---------------------------------------------------------------- properties

describe('invert', () => {
  it('is an involution — invert(invert(op)) is the original', () => {
    fc.assert(
      fc.property(intents(POOL_A), (list) => {
        for (const op of realize(emptyDoc(), list).ops) {
          expect(invert(invert(op))).toEqual(op)
        }
      }),
    )
  })

  it('a transaction and its inverse round-trip the document', () => {
    fc.assert(
      fc.property(intents(POOL_A), (list) => {
        const base = emptyDoc()
        const { ops, doc: after } = realize(base, list)
        // No gap, so nothing to rebase through: the raw inverse must land home.
        expect(applyAll(after, invertAll(ops))).toEqual(base)
      }),
    )
  })
})

describe('rebase', () => {
  it('over an empty gap is the identity', () => {
    fc.assert(
      fc.property(intents(POOL_A), (list) => {
        const { ops } = realize(emptyDoc(), list)
        const out = rebase(ops, [])
        expect(out.every((d) => d.kind === 'ok')).toBe(true)
        expect(rebased(out)).toEqual(ops)
      }),
    )
  })

  it('never rewrites a position and never fabricates an op', () => {
    fc.assert(
      fc.property(intents(POOL_A), intents(POOL_A), (a, b) => {
        const base = emptyDoc()
        const { ops, doc } = realize(base, a)
        const { ops: gap } = realize(doc, b)
        for (const d of rebase(ops, gapOf(gap))) {
          // Identity, not just equality: rebase classifies, it does not rebuild.
          expect(ops).toContain(d.op)
        }
      }),
    )
  })

  it('drops every op addressing an entity the gap deleted', () => {
    fc.assert(
      fc.property(intents(POOL_A), fc.constantFrom(...POOL_A), (a, victim) => {
        const base = emptyDoc()
        const { ops, doc } = realize(base, a)
        const gap: Op[] = doc.nodes[victim]
          ? [{ t: 'del', entity: victim, node: {}, parent: doc.nodes[victim].parent, pos: doc.nodes[victim].pos }]
          : []
        fc.pre(gap.length > 0)
        for (const d of rebase(ops, gapOf(gap))) {
          // `add` is exempt: re-creating something the gap removed is coherent.
          if (d.op.entity === victim && d.op.t !== 'add') {
            expect(d.kind).toBe('dropped')
          }
        }
      }),
    )
  })

  it('flags a concurrent write to the same field rather than resurrecting a stale value', () => {
    const base = emptyDoc()
    const { ops, doc } = realize(base, [
      { k: 'add', e: 'a1', p: ROOT, pos: 'm' },
      { k: 'set', e: 'a1', f: 'fill', v: 1 },
    ])
    const { ops: gap } = realize(doc, [{ k: 'set', e: 'a1', f: 'fill', v: 2 }])
    const out = rebase(invertAll(ops.slice(1)), gapOf(gap))
    expect(out.map((d) => d.kind)).toEqual(['conflict'])
    expect(out[0].kind === 'conflict' && out[0].reason).toBe('field-overwritten')
  })

  it('names the actor behind a conflict, so policy can tell mine from theirs', () => {
    const base = emptyDoc()
    const { ops, doc } = realize(base, [
      { k: 'add', e: 'a1', p: ROOT, pos: 'm' },
      { k: 'set', e: 'a1', f: 'fill', v: 1 },
    ])
    const { ops: gap } = realize(doc, [{ k: 'set', e: 'a1', f: 'fill', v: 2 }])
    const inverse = invertAll(ops.slice(1))

    const mine = rebase(inverse, gapOf(gap, LOCAL_ACTOR))
    expect(isForeignConflict(mine[0], LOCAL_ACTOR)).toBe(false)
    // `refuse` lets my own later edit through — refusing it would make undo
    // silently do nothing in ordinary single-user work.
    expect(resolve(mine, 'refuse', LOCAL_ACTOR).ops).toHaveLength(1)

    const theirs = rebase(inverse, gapOf(gap, 'someone-else'))
    expect(isForeignConflict(theirs[0], LOCAL_ACTOR)).toBe(true)
    const out = resolve(theirs, 'refuse', LOCAL_ACTOR)
    expect(out.ops).toHaveLength(0)
    expect(out.refused).toHaveLength(1)
    // `apply` clobbers regardless — the Phase 1 canvas policy.
    expect(resolve(theirs, 'apply', LOCAL_ACTOR).ops).toHaveLength(1)
  })

  /**
   * The property the whole design rests on: undoing a transaction after other,
   * unrelated work has landed must leave exactly that other work standing —
   * not the state as it was, and not the other work reverted along with it.
   */
  it('undo over a disjoint gap leaves exactly the gap\'s effect', () => {
    fc.assert(
      fc.property(intents(POOL_A), intents(POOL_B), (a, b) => {
        const base = emptyDoc()
        const { ops, doc: afterOps } = realize(base, a)
        const { ops: gap, doc: afterGap } = realize(afterOps, b)

        const undone = applyAll(afterGap, rebased(rebase(invertAll(ops), gapOf(gap))))
        // Disjoint entity pools, so the gap alone reaches the same state.
        expect(undone).toEqual(applyAll(base, gap))
      }),
    )
  })
})
