quarkus:
  live-reload:
    instrumentation: true

  liquibase:
    migrate-at-start: true
    clean-at-start: true

  rest-client:
    logging:
      body-limit: 1024
      scope: request-response
    figma-api:
      url: https://api.figma.com
    github-api:
      url: https://api.github.com
    github-auth:
      url: https://github.com

mp:
  jwt:
    verify:
      issuer: ux-plugin
      publickey:
        location: classpath:META-INF/resources/publicKey-dev.pem

smallrye:
  jwt:
    sign:
      key:
        location: classpath:META-INF/resources/privateKey-dev.pem

auth:
  access-token-ttl-s: 90000  # 15 minutes
  refresh-token-ttl-s: 2592000  # 30 days
  figma:
    client-id: client id
    client-secret: client secret
    auth-url: https://www.figma.com/oauth
    token-url: https://api.figma.com/v1/oauth/token
    login-redirect-uri: http://localhost:8080/auth/figma/callback
    connect-redirect-uri: http://localhost:8080/auth/figma/connect/callback
    login:
      random-key:
        max-retries: 5
      timeout-sec: 10
    rest-client:
      access-token:
        redis-key-prefix: "figma-client:"
    read-token:
      redis-key-prefix: "figma-read-token:"
    write-token:
      redis-key-prefix: "figma-write-token:"

  github:
    client-id: github-client-id
    client-secret: github-client-secret
    auth-url: https://github.com/login/oauth/authorize
    token-url: https://github.com/login/oauth/access_token
    login-redirect-uri: http://localhost:8080/auth/github/callback
    connect-redirect-uri: http://localhost:8080/auth/github/connect/callback
    login:
      random-key:
        max-retries: 5
      timeout-sec: 60
    rest-client:
      access-token:
        redis-key-prefix: "github-client:"
    read-token:
      redis-key-prefix: "github-read-token:"
    write-token:
      redis-key-prefix: "github-write-token:"

apps:
  encryption-key-ttl-s: 3600