quarkus:
  liquibase:
    migrate-at-start: true
    clean-at-start: true
mp:
  jwt:
    verify:
      issuer: ux-plugin
      publickey:
        location: classpath:META-INF/resources/publicKey-dev.pem

smallrye:
  jwt:
    sign:
      key:
        location: classpath:META-INF/resources/privateKey-dev.pem

openai:
  api:
    base-url:
      http://localhost:8003
    key: nothing