# Quarkus YAML configuration
quarkus:
  application:
    name: figma-plugin-api

  # HTTP configuration
  http:
    port: "${API_PORT:8003}"
    host: "${API_HOST:0.0.0.0}"

    # CORS configuration
    cors:
      enabled: true
      origins: "*"
      methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      headers: Authorization,Content-Type,Accept
      exposed-headers: Content-Disposition
      access-control-max-age: 3600

  # OpenAPI and Swagger UI
  swagger-ui:
    always-include: true
  smallrye-openapi:
    path: /openapi
    info-title: Figma Plugin API
    info-version: 0.0.1
    info-description: API for Figma Plugin

  # Database configuration
  datasource:
    db-kind: postgresql
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:password}"
    reactive:
      url: "postgresql://${DB_HOST:localhost}:${DB_PORT:5430}/${DB_NAME:figma_plugin}"

    # JDBC configuration for liquibase
    jdbc:
      url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5430}/${DB_NAME:figma_plugin}"
      driver: org.postgresql.Driver

  
  # Hibernate ORM configuration
  hibernate-orm:
    database:
      generation: none
    log:
      sql: true
    physical-naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Liquibase configuration
  liquibase:
    migrate-at-start: true
    change-log: db/changelog/master.yaml

  rest-client:
    ai-server-client:
      url: "${AI_SERVER_URL:http://localhost:8002}"

openai:
  api.key: "${OPENAI_API_KEY}"
  project.id: "${OPENAI_PROJECT_ID}"
  org.id: "${OPENAI_ORG_ID}"