services:
  cdn:
    build:
      context: ./cdn
      dockerfile: Dockerfile
    ports:
      - "${CDN_PORT:-8082}:8080"
    volumes:
      - ./cdn/content:/usr/share/nginx/html:ro
    container_name: figma-plugin-cdn
