// GENERATED by ~/.claude/hooks/penpot-worktree-terminal — safe to delete.
// (a) Gives the page a worktree-identifying <title>, so this worktree's Chrome
//     window is tellable apart from every other worktree's.
// (b) Pins the dependency-scan entry to index.html. packages/penpot-exporter/ui-src/
//     index.html also sits under this root, and its @ui/* aliases exist only in that
//     package's own config — so Vite's default `**/*.html` scan crawls it and the
//     first cold start fails with "Failed to run dependency scan", silently skipping
//     pre-bundling (which is why a second start looks fine: the cache is warm).
import base from './vite.config'

const TITLE = 'skia-abstraction-vello-backend 5306'

export default async (env: any) => {
  const cfg: any = typeof base === 'function' ? await (base as any)(env) : base
  return {
    ...cfg,
    optimizeDeps: { ...(cfg.optimizeDeps ?? {}), entries: ['index.html'] },
    plugins: [
      ...(cfg.plugins ?? []),
      {
        name: 'worktree-title',
        transformIndexHtml: (html: string) =>
          html.replace(/<title>[\s\S]*?<\/title>/, `<title>${TITLE}</title>`),
      },
    ],
  }
}
