/* eslint-disable */
// AUTO-GENERATED by compile.test.ts — proves the emitter output typechecks as React.
import { useState } from 'react'

export function TodoDemo() {
  const [items, setItems] = useState<any[]>([])
  const isEmpty = (items.length === 0)

  const handle_addBtn_press = () => {
    setItems((prev) => [...prev, { label: "" }])
  }

  return (
    <div data-node-id="page" style={{ "boxSizing": "border-box" }}>
      <div data-node-id="addBtn" disabled={isEmpty} onClick={handle_addBtn_press} style={{ "boxSizing": "border-box" }}>Add</div>
      <div data-node-id="list" style={{ "boxSizing": "border-box" }}>
        {items.map((item) => (
          <div data-node-id="row" key={item.id} data-instance-key={item.id} style={{ "boxSizing": "border-box" }}>{item.label}</div>
        ))}
      </div>
    </div>
  )
}
