/* eslint-disable */
// AUTO-GENERATED by compile.test.ts — proves the emitter output typechecks as React.
import { useState } from 'react'

/** Enter/Space activation for role="button" and role="link" boxes. */
const onActivate = (fn: () => void, keys: string[]) => (e: { key: string; preventDefault: () => void }) => {
  if (keys.includes(e.key)) {
    e.preventDefault()
    fn()
  }
}

export function TodoDemo() {
  const [items, setItems] = useState<any[]>([])
  const isEmpty = (items.length === 0)

  const handle_addBtn_press = () => {
    setItems((prev) => [...prev, { label: "" }])
  }

  return (
    <div data-node-id="page" style={{ "boxSizing": "border-box" }}>
      <div data-node-id="addBtn" disabled={isEmpty} onClick={handle_addBtn_press} role="button" tabIndex={0} onKeyDown={onActivate(handle_addBtn_press, ["Enter"," "])} style={{ "boxSizing": "border-box", "cursor": "pointer" }}>Add</div>
      <div data-node-id="list" role="list" style={{ "boxSizing": "border-box" }}>
        {items.map((item) => (
          <div data-node-id="row" key={item.id} data-instance-key={item.id} role="listitem" style={{ "boxSizing": "border-box" }}>{item.label}</div>
        ))}
      </div>
    </div>
  )
}
