/* eslint-disable */
// AUTO-GENERATED by compile.test.ts — proves the emitter output typechecks as React.
import { useState } from 'react'

export function TodoDemo() {
  const [items, setItems] = useState<any[]>([])
  const isEmpty = (items.length === 0)

  const handle_addBtn_press = () => {
    setItems((prev) => [...prev, { label: "" }])
  }

  return (
    <div data-node-id="page">
      <button data-node-id="addBtn" disabled={isEmpty} onClick={handle_addBtn_press}>Add</button>
      <ul data-node-id="list">
        {items.map((item) => (
          <li data-node-id="row" key={item.id} data-instance-key={item.id}>{item.label}</li>
        ))}
      </ul>
    </div>
  )
}
